// module.exports = {
//   BAD_REQUEST: {
//     STATUS: 400,
//     DEFAULT_MESSAGE: "INVALID REQUEST DATA",
//   },
//   UNAUTHORIZED: {
//     STATUS: 401,
//     DEFAULT_MESSAGE: "AUTHORIZATION REQUIRED",
//   },
//   PERMISSION: {
//     STATUS: 403,
//     DEFAULT_MESSAGE: "NO PERMISSION TO EXECUTE ACTION",
//   },
//   NOT_FOUND: {
//     STATUS: 404,
//     DEFAULT_MESSAGE: "REQUESTED RESOURCE NOT FOUND",
//   },
//   CONFLICT: {
//     STATUS: 409,
//     DEFAULT_MESSAGE: "USER ALREADY EXISTS",
//   },
//   INTERNAL_SERVER_ERROR: {
//     STATUS: 500,
//     DEFAULT_MESSAGE: "AN ERROR HAS OCCURED ON THE SERVER",
//   },
// };
